-- Script to initialize the database schema for the BitBlik Coordinator

-- Create the offers table
CREATE TABLE IF NOT EXISTS offers (
  id UUID PRIMARY KEY,
  amount_sats BIGINT NOT NULL,
  maker_fees BIGINT NOT NULL, -- Renamed from fee_sats
  maker_pubkey TEXT NOT NULL,
  taker_pubkey TEXT,
  taker_invoice TEXT, -- Added to store resolved invoice before payment attempt
  maker_refund_invoice TEXT,
  blik_code TEXT,
  hold_invoice_payment_hash TEXT UNIQUE NOT NULL,
  hold_invoice_preimage TEXT NOT NULL,
  status TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ,
  reserved_at TIMESTAMPTZ,
  blik_received_at TIMESTAMPTZ,
  maker_confirmed_at TIMESTAMPTZ,
  settled_at TIMESTAMPTZ,
  taker_paid_at TIMESTAMPTZ,
  taker_fees BIGINT NULL, -- Renamed from taker_fees_sats
  taker_payment_failure_reason TEXT NULL,
  category TEXT
);

-- Add index for faster lookups by status
CREATE INDEX IF NOT EXISTS idx_offers_status ON offers (status);

-- Optional: Add other indexes based on query patterns
CREATE INDEX IF NOT EXISTS idx_offers_maker_pubkey ON offers (maker_pubkey);
CREATE INDEX IF NOT EXISTS idx_offers_taker_pubkey ON offers (taker_pubkey);

-- Durable outgoing payout/refund attempts. The legacy offer columns above
-- hold either a BOLT11 invoice or a BOLT12 offer; attempts make that type
-- explicit and prevent an indeterminate NWC request from being sent twice.
CREATE TABLE IF NOT EXISTS outgoing_payment_attempts (
  id UUID PRIMARY KEY,
  offer_id UUID NOT NULL REFERENCES offers(id) ON DELETE CASCADE,
  purpose TEXT NOT NULL,
  generation INTEGER NOT NULL,
  payment_type TEXT NOT NULL,
  bolt11_invoice TEXT,
  bolt12_offer TEXT,
  expected_amount_sats BIGINT NOT NULL,
  fee_limit_sats BIGINT,
  backend_type TEXT NOT NULL,
  backend_payment_id TEXT,
  state TEXT NOT NULL,
  payment_hash TEXT,
  preimage TEXT,
  payer_proof TEXT,
  fee_paid_sats BIGINT,
  failure_reason TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  settled_at TIMESTAMPTZ,
  UNIQUE (offer_id, purpose, generation),
  CHECK (
    (payment_type = 'bolt11' AND bolt11_invoice IS NOT NULL AND bolt12_offer IS NULL)
    OR
    (payment_type = 'bolt12' AND bolt12_offer IS NOT NULL AND bolt11_invoice IS NULL)
  ),
  CHECK (state IN ('prepared','submitted','pending','succeeded','failed','unknown'))
);

CREATE INDEX IF NOT EXISTS idx_outgoing_attempts_nonterminal
  ON outgoing_payment_attempts (state, updated_at)
  WHERE state IN ('prepared','submitted','pending','unknown');

-- Audit logs persisted from application logger (onRecord listener)
CREATE TABLE IF NOT EXISTS log_audit (
  id BIGSERIAL PRIMARY KEY,
  offer_id TEXT,
  action TEXT NOT NULL,
  level TEXT NOT NULL,
  logger_name TEXT NOT NULL,
  message TEXT NOT NULL,
  error TEXT,
  stack_trace TEXT,
  metadata JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_log_audit_offer_id ON log_audit (offer_id);
CREATE INDEX IF NOT EXISTS idx_log_audit_action ON log_audit (action);

-- Per-offer state transition trail for YAML-driven flows.
-- Records every transition an offer goes through: user actions, timer/timeout
-- firings, and coordinator-driven (auto) follow-ups. Supersedes log_audit in
-- that mode.
CREATE TABLE IF NOT EXISTS offer_state_history (
  id BIGSERIAL PRIMARY KEY,
  offer_id UUID NOT NULL,
  from_state TEXT,
  to_state TEXT NOT NULL,
  trigger_type TEXT NOT NULL, -- user_action | timeout | auto | coordinator
  event TEXT,                 -- rpc/event or action name when known
  actor TEXT,                 -- maker | taker | coordinator | server
  actor_pubkey TEXT,
  metadata JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_offer_state_history_offer
  ON offer_state_history (offer_id, created_at, id);

-- Grant necessary privileges (adjust user 'user' if needed)
-- GRANT ALL PRIVILEGES ON TABLE offers TO "user";
-- GRANT USAGE, SELECT ON SEQUENCE offers_id_seq TO "user"; -- If using SERIAL instead of UUID

-- Note: The DatabaseService code uses UUIDs generated by the application.
-- If you prefer auto-incrementing IDs, change 'id UUID PRIMARY KEY' to
-- 'id SERIAL PRIMARY KEY'.
