-- Script to initialize the database schema for the BitBlik Coordinator

-- Create the offers table
CREATE TABLE IF NOT EXISTS offers (
  id UUID PRIMARY KEY,
  amount_sats BIGINT NOT NULL,
  maker_fees BIGINT NOT NULL, -- Renamed from fee_sats
  maker_pubkey TEXT NOT NULL,
  taker_pubkey TEXT,
  taker_lightning_address TEXT, -- Added for LNURL payout
  taker_invoice TEXT, -- Added to store resolved invoice before payment attempt
  blik_code TEXT,
  hold_invoice_payment_hash TEXT UNIQUE NOT NULL,
  hold_invoice_preimage TEXT NOT NULL,
  status TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ,
  reserved_at TIMESTAMPTZ,
  blik_received_at TIMESTAMPTZ,
  maker_confirmed_at TIMESTAMPTZ,
  settled_at TIMESTAMPTZ,
  taker_paid_at TIMESTAMPTZ,
  taker_fees BIGINT NULL, -- Renamed from taker_fees_sats
  taker_payment_failure_reason TEXT NULL,
  category TEXT
);

-- Add index for faster lookups by status
CREATE INDEX IF NOT EXISTS idx_offers_status ON offers (status);

-- Optional: Add other indexes based on query patterns
CREATE INDEX IF NOT EXISTS idx_offers_maker_pubkey ON offers (maker_pubkey);
CREATE INDEX IF NOT EXISTS idx_offers_taker_pubkey ON offers (taker_pubkey);

-- Audit logs persisted from application logger (onRecord listener)
CREATE TABLE IF NOT EXISTS log_audit (
  id BIGSERIAL PRIMARY KEY,
  offer_id TEXT,
  action TEXT NOT NULL,
  level TEXT NOT NULL,
  logger_name TEXT NOT NULL,
  message TEXT NOT NULL,
  error TEXT,
  stack_trace TEXT,
  metadata JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_log_audit_offer_id ON log_audit (offer_id);
CREATE INDEX IF NOT EXISTS idx_log_audit_action ON log_audit (action);

-- Per-offer state transition trail for FLOW_MODE generic (yaml-driven flows).
-- Records every transition an offer goes through: user actions, timer/timeout
-- firings, and coordinator-driven (auto) follow-ups. Supersedes log_audit in
-- that mode.
CREATE TABLE IF NOT EXISTS offer_state_history (
  id BIGSERIAL PRIMARY KEY,
  offer_id UUID NOT NULL,
  from_state TEXT,
  to_state TEXT NOT NULL,
  trigger_type TEXT NOT NULL, -- user_action | timeout | auto | coordinator
  event TEXT,                 -- rpc/event or action name when known
  actor TEXT,                 -- maker | taker | coordinator | server
  actor_pubkey TEXT,
  metadata JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_offer_state_history_offer
  ON offer_state_history (offer_id, created_at, id);

-- Grant necessary privileges (adjust user 'user' if needed)
-- GRANT ALL PRIVILEGES ON TABLE offers TO "user";
-- GRANT USAGE, SELECT ON SEQUENCE offers_id_seq TO "user"; -- If using SERIAL instead of UUID

-- Note: The DatabaseService code uses UUIDs generated by the application.
-- If you prefer auto-incrementing IDs, change 'id UUID PRIMARY KEY' to
-- 'id SERIAL PRIMARY KEY'.
