// Mocks generated by Mockito 5.4.6 from annotations
// in bitblik_coordinator/test/coordinator_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;
import 'dart:convert' as _i12;
import 'dart:typed_data' as _i14;

import 'package:bitblik_coordinator/src/models/cancel_invoice_result.dart'
    as _i4;
import 'package:bitblik_coordinator/src/models/create_hold_invoice_result.dart'
    as _i3;
import 'package:bitblik_coordinator/src/models/invoice_details.dart' as _i6;
import 'package:bitblik_coordinator/src/models/invoice_update.dart' as _i11;
import 'package:bitblik_coordinator/src/models/pay_invoice_result.dart' as _i5;
import 'package:bitblik_coordinator/src/services/database_service.dart' as _i8;
import 'package:bitblik_coordinator/src/services/payment_service.dart' as _i10;
import 'package:bitblik_core/core.dart' as _i2;
import 'package:http/http.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i13;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeOffer_0 extends _i1.SmartFake implements _i2.Offer {
  _FakeOffer_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCreateHoldInvoiceResult_1 extends _i1.SmartFake
    implements _i3.CreateHoldInvoiceResult {
  _FakeCreateHoldInvoiceResult_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCancelInvoiceResult_2 extends _i1.SmartFake
    implements _i4.CancelInvoiceResult {
  _FakeCancelInvoiceResult_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePayInvoiceResult_3 extends _i1.SmartFake
    implements _i5.PayInvoiceResult {
  _FakePayInvoiceResult_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInvoiceDetails_4 extends _i1.SmartFake
    implements _i6.InvoiceDetails {
  _FakeInvoiceDetails_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_5 extends _i1.SmartFake implements _i7.Response {
  _FakeResponse_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamedResponse_6 extends _i1.SmartFake
    implements _i7.StreamedResponse {
  _FakeStreamedResponse_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DatabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseService extends _i1.Mock implements _i8.DatabaseService {
  MockDatabaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get recordStateHistory => (super.noSuchMethod(
        Invocation.getter(#recordStateHistory),
        returnValue: false,
      ) as bool);

  @override
  set recordStateHistory(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #recordStateHistory,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<void> connect() => (super.noSuchMethod(
        Invocation.method(
          #connect,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> disconnect() => (super.noSuchMethod(
        Invocation.method(
          #disconnect,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> recordOfferTransition({
    required String? offerId,
    required String? fromState,
    required String? toState,
    _i8.StateTransitionMeta? meta,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #recordOfferTransition,
          [],
          {
            #offerId: offerId,
            #fromState: fromState,
            #toState: toState,
            #meta: meta,
          },
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<List<Map<String, dynamic>>> getOfferStateHistory(
          String? offerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOfferStateHistory,
          [offerId],
        ),
        returnValue: _i9.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i9.Future<List<Map<String, dynamic>>>);

  @override
  _i9.Future<void> saveTelegramOfferMessage({
    required String? offerId,
    required String? chatId,
    required int? messageId,
    required String? messageText,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveTelegramOfferMessage,
          [],
          {
            #offerId: offerId,
            #chatId: chatId,
            #messageId: messageId,
            #messageText: messageText,
          },
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<List<_i8.TelegramOfferMessage>> getTelegramOfferMessages(
          String? offerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTelegramOfferMessages,
          [offerId],
        ),
        returnValue: _i9.Future<List<_i8.TelegramOfferMessage>>.value(
            <_i8.TelegramOfferMessage>[]),
      ) as _i9.Future<List<_i8.TelegramOfferMessage>>);

  @override
  _i9.Future<void> deleteTelegramOfferMessages(String? offerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteTelegramOfferMessages,
          [offerId],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> insertAuditLog({
    required String? level,
    required String? loggerName,
    required String? message,
    required String? action,
    String? offerId,
    String? error,
    String? stackTrace,
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertAuditLog,
          [],
          {
            #level: level,
            #loggerName: loggerName,
            #message: message,
            #action: action,
            #offerId: offerId,
            #error: error,
            #stackTrace: stackTrace,
            #metadata: metadata,
          },
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<_i2.Offer> createOffer(_i2.Offer? offer) => (super.noSuchMethod(
        Invocation.method(
          #createOffer,
          [offer],
        ),
        returnValue: _i9.Future<_i2.Offer>.value(_FakeOffer_0(
          this,
          Invocation.method(
            #createOffer,
            [offer],
          ),
        )),
      ) as _i9.Future<_i2.Offer>);

  @override
  _i9.Future<_i2.Offer?> getOfferById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getOfferById,
          [id],
        ),
        returnValue: _i9.Future<_i2.Offer?>.value(),
      ) as _i9.Future<_i2.Offer?>);

  @override
  _i9.Future<_i2.Offer?> getOfferByPaymentHash(String? paymentHash) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOfferByPaymentHash,
          [paymentHash],
        ),
        returnValue: _i9.Future<_i2.Offer?>.value(),
      ) as _i9.Future<_i2.Offer?>);

  @override
  _i9.Future<List<_i2.Offer>> getOffersByStatus(
    _i2.OfferStatus? status, {
    int? limit = 50,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOffersByStatus,
          [status],
          {
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue: _i9.Future<List<_i2.Offer>>.value(<_i2.Offer>[]),
      ) as _i9.Future<List<_i2.Offer>>);

  @override
  _i9.Future<List<_i2.Offer>> getOffersByRawStatus(
    String? status, {
    int? limit = 1000,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOffersByRawStatus,
          [status],
          {
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue: _i9.Future<List<_i2.Offer>>.value(<_i2.Offer>[]),
      ) as _i9.Future<List<_i2.Offer>>);

  @override
  _i9.Future<List<_i2.Offer>> getOffersNotInRawStatuses(
    List<String>? terminalStatuses, {
    int? limit = 5000,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOffersNotInRawStatuses,
          [terminalStatuses],
          {#limit: limit},
        ),
        returnValue: _i9.Future<List<_i2.Offer>>.value(<_i2.Offer>[]),
      ) as _i9.Future<List<_i2.Offer>>);

  @override
  _i9.Future<bool> updateOfferRawStatusIfCurrent(
    String? id,
    String? newStatus, {
    List<String>? expectedCurrentStatuses,
    String? expectedTakerPubkey,
    String? takerPubkey,
    String? code,
    String? takerInvoice,
    String? takerLightningAddress,
    DateTime? reservedAt,
    DateTime? codeReceivedAt,
    DateTime? takerChargedAt,
    DateTime? makerConfirmedAt,
    DateTime? settledAt,
    DateTime? takerPaidAt,
    DateTime? disputeAt,
    int? takerFees,
    String? failureReason,
    bool? clearTakerFields = false,
    bool? preserveCodeOnClear = false,
    _i8.StateTransitionMeta? transitionMeta,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateOfferRawStatusIfCurrent,
          [
            id,
            newStatus,
          ],
          {
            #expectedCurrentStatuses: expectedCurrentStatuses,
            #expectedTakerPubkey: expectedTakerPubkey,
            #takerPubkey: takerPubkey,
            #code: code,
            #takerInvoice: takerInvoice,
            #takerLightningAddress: takerLightningAddress,
            #reservedAt: reservedAt,
            #codeReceivedAt: codeReceivedAt,
            #takerChargedAt: takerChargedAt,
            #makerConfirmedAt: makerConfirmedAt,
            #settledAt: settledAt,
            #takerPaidAt: takerPaidAt,
            #disputeAt: disputeAt,
            #takerFees: takerFees,
            #failureReason: failureReason,
            #clearTakerFields: clearTakerFields,
            #preserveCodeOnClear: preserveCodeOnClear,
            #transitionMeta: transitionMeta,
          },
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<bool> updateTakerInvoice(
    String? id,
    String? takerInvoice,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTakerInvoice,
          [
            id,
            takerInvoice,
          ],
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<bool> updateTakerInvoiceFees(
    String? id,
    int? fees,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTakerInvoiceFees,
          [
            id,
            fees,
          ],
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<bool> updateOfferStatus(
    String? id,
    _i2.OfferStatus? newStatus, {
    String? takerPubkey,
    String? blikCode,
    String? takerInvoice,
    String? takerLightningAddress,
    DateTime? reservedAt,
    DateTime? blikReceivedAt,
    DateTime? takerChargedAt,
    _i2.DisputeEscalationReason? disputeEscalationReason,
    int? takerFees,
    String? failureReason,
    _i8.StateTransitionMeta? transitionMeta,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateOfferStatus,
          [
            id,
            newStatus,
          ],
          {
            #takerPubkey: takerPubkey,
            #blikCode: blikCode,
            #takerInvoice: takerInvoice,
            #takerLightningAddress: takerLightningAddress,
            #reservedAt: reservedAt,
            #blikReceivedAt: blikReceivedAt,
            #takerChargedAt: takerChargedAt,
            #disputeEscalationReason: disputeEscalationReason,
            #takerFees: takerFees,
            #failureReason: failureReason,
            #transitionMeta: transitionMeta,
          },
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<bool> updateOfferStatusIfCurrentStatus(
    String? id,
    _i2.OfferStatus? newStatus,
    List<_i2.OfferStatus>? expectedCurrentStatuses, {
    String? takerPubkey,
    String? blikCode,
    String? takerInvoice,
    String? takerLightningAddress,
    DateTime? reservedAt,
    DateTime? blikReceivedAt,
    DateTime? takerChargedAt,
    _i2.DisputeEscalationReason? disputeEscalationReason,
    int? takerFees,
    String? failureReason,
    String? expectedTakerPubkey,
    _i8.StateTransitionMeta? transitionMeta,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateOfferStatusIfCurrentStatus,
          [
            id,
            newStatus,
            expectedCurrentStatuses,
          ],
          {
            #takerPubkey: takerPubkey,
            #blikCode: blikCode,
            #takerInvoice: takerInvoice,
            #takerLightningAddress: takerLightningAddress,
            #reservedAt: reservedAt,
            #blikReceivedAt: blikReceivedAt,
            #takerChargedAt: takerChargedAt,
            #disputeEscalationReason: disputeEscalationReason,
            #takerFees: takerFees,
            #failureReason: failureReason,
            #expectedTakerPubkey: expectedTakerPubkey,
            #transitionMeta: transitionMeta,
          },
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<bool> cancelOffer(
    String? id,
    String? makerPubkey,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelOffer,
          [
            id,
            makerPubkey,
          ],
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<List<_i2.Offer>> getMyActiveOffers(String? userPubkey) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMyActiveOffers,
          [userPubkey],
        ),
        returnValue: _i9.Future<List<_i2.Offer>>.value(<_i2.Offer>[]),
      ) as _i9.Future<List<_i2.Offer>>);

  @override
  _i9.Future<List<_i2.Offer>> getOffersFromLastHours() => (super.noSuchMethod(
        Invocation.method(
          #getOffersFromLastHours,
          [],
        ),
        returnValue: _i9.Future<List<_i2.Offer>>.value(<_i2.Offer>[]),
      ) as _i9.Future<List<_i2.Offer>>);
}

/// A class which mocks [PaymentService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaymentService extends _i1.Mock implements _i10.PaymentService {
  MockPaymentService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<void> connect() => (super.noSuchMethod(
        Invocation.method(
          #connect,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> disconnect() => (super.noSuchMethod(
        Invocation.method(
          #disconnect,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<_i3.CreateHoldInvoiceResult> createHoldInvoice({
    required int? amountSats,
    required String? memo,
    required String? paymentHashHex,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createHoldInvoice,
          [],
          {
            #amountSats: amountSats,
            #memo: memo,
            #paymentHashHex: paymentHashHex,
          },
        ),
        returnValue: _i9.Future<_i3.CreateHoldInvoiceResult>.value(
            _FakeCreateHoldInvoiceResult_1(
          this,
          Invocation.method(
            #createHoldInvoice,
            [],
            {
              #amountSats: amountSats,
              #memo: memo,
              #paymentHashHex: paymentHashHex,
            },
          ),
        )),
      ) as _i9.Future<_i3.CreateHoldInvoiceResult>);

  @override
  _i9.Future<void> settleInvoice({required String? preimageHex}) =>
      (super.noSuchMethod(
        Invocation.method(
          #settleInvoice,
          [],
          {#preimageHex: preimageHex},
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<_i4.CancelInvoiceResult> cancelInvoice(
          {required String? paymentHashHex}) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelInvoice,
          [],
          {#paymentHashHex: paymentHashHex},
        ),
        returnValue: _i9.Future<_i4.CancelInvoiceResult>.value(
            _FakeCancelInvoiceResult_2(
          this,
          Invocation.method(
            #cancelInvoice,
            [],
            {#paymentHashHex: paymentHashHex},
          ),
        )),
      ) as _i9.Future<_i4.CancelInvoiceResult>);

  @override
  _i9.Future<_i5.PayInvoiceResult> payInvoice({
    required String? invoice,
    int? amountSat,
    int? feeLimitSat,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #payInvoice,
          [],
          {
            #invoice: invoice,
            #amountSat: amountSat,
            #feeLimitSat: feeLimitSat,
          },
        ),
        returnValue:
            _i9.Future<_i5.PayInvoiceResult>.value(_FakePayInvoiceResult_3(
          this,
          Invocation.method(
            #payInvoice,
            [],
            {
              #invoice: invoice,
              #amountSat: amountSat,
              #feeLimitSat: feeLimitSat,
            },
          ),
        )),
      ) as _i9.Future<_i5.PayInvoiceResult>);

  @override
  _i9.Stream<_i11.InvoiceUpdate> subscribeToInvoiceUpdates(
          {required String? paymentHashHex}) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribeToInvoiceUpdates,
          [],
          {#paymentHashHex: paymentHashHex},
        ),
        returnValue: _i9.Stream<_i11.InvoiceUpdate>.empty(),
      ) as _i9.Stream<_i11.InvoiceUpdate>);

  @override
  _i9.Future<_i6.InvoiceDetails> lookupInvoice(
          {required String? paymentHashHex}) =>
      (super.noSuchMethod(
        Invocation.method(
          #lookupInvoice,
          [],
          {#paymentHashHex: paymentHashHex},
        ),
        returnValue: _i9.Future<_i6.InvoiceDetails>.value(_FakeInvoiceDetails_4(
          this,
          Invocation.method(
            #lookupInvoice,
            [],
            {#paymentHashHex: paymentHashHex},
          ),
        )),
      ) as _i9.Future<_i6.InvoiceDetails>);

  @override
  _i9.Future<_i5.PayInvoiceResult?> reconcileOutgoingPayment(
          {required String? invoice}) =>
      (super.noSuchMethod(
        Invocation.method(
          #reconcileOutgoingPayment,
          [],
          {#invoice: invoice},
        ),
        returnValue: _i9.Future<_i5.PayInvoiceResult?>.value(),
      ) as _i9.Future<_i5.PayInvoiceResult?>);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockClient extends _i1.Mock implements _i7.Client {
  MockClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i7.Response> head(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [url],
          {#headers: headers},
        ),
        returnValue: _i9.Future<_i7.Response>.value(_FakeResponse_5(
          this,
          Invocation.method(
            #head,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i9.Future<_i7.Response>);

  @override
  _i9.Future<_i7.Response> get(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [url],
          {#headers: headers},
        ),
        returnValue: _i9.Future<_i7.Response>.value(_FakeResponse_5(
          this,
          Invocation.method(
            #get,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i9.Future<_i7.Response>);

  @override
  _i9.Future<_i7.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i12.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i9.Future<_i7.Response>.value(_FakeResponse_5(
          this,
          Invocation.method(
            #post,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i9.Future<_i7.Response>);

  @override
  _i9.Future<_i7.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i12.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i9.Future<_i7.Response>.value(_FakeResponse_5(
          this,
          Invocation.method(
            #put,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i9.Future<_i7.Response>);

  @override
  _i9.Future<_i7.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i12.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i9.Future<_i7.Response>.value(_FakeResponse_5(
          this,
          Invocation.method(
            #patch,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i9.Future<_i7.Response>);

  @override
  _i9.Future<_i7.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i12.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i9.Future<_i7.Response>.value(_FakeResponse_5(
          this,
          Invocation.method(
            #delete,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i9.Future<_i7.Response>);

  @override
  _i9.Future<String> read(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #read,
          [url],
          {#headers: headers},
        ),
        returnValue: _i9.Future<String>.value(_i13.dummyValue<String>(
          this,
          Invocation.method(
            #read,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i9.Future<String>);

  @override
  _i9.Future<_i14.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readBytes,
          [url],
          {#headers: headers},
        ),
        returnValue: _i9.Future<_i14.Uint8List>.value(_i14.Uint8List(0)),
      ) as _i9.Future<_i14.Uint8List>);

  @override
  _i9.Future<_i7.StreamedResponse> send(_i7.BaseRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #send,
          [request],
        ),
        returnValue:
            _i9.Future<_i7.StreamedResponse>.value(_FakeStreamedResponse_6(
          this,
          Invocation.method(
            #send,
            [request],
          ),
        )),
      ) as _i9.Future<_i7.StreamedResponse>);

  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
