// Mocks generated by Mockito 5.4.6 from annotations
// in bitblik_coordinator/test/test_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i11;

import 'package:bitblik_coordinator/src/models/bolt12_offer_info.dart' as _i8;
import 'package:bitblik_coordinator/src/models/cancel_invoice_result.dart'
    as _i5;
import 'package:bitblik_coordinator/src/models/create_hold_invoice_result.dart'
    as _i4;
import 'package:bitblik_coordinator/src/models/invoice_details.dart' as _i7;
import 'package:bitblik_coordinator/src/models/invoice_update.dart' as _i13;
import 'package:bitblik_coordinator/src/models/outgoing_payment_attempt.dart'
    as _i2;
import 'package:bitblik_coordinator/src/models/pay_invoice_result.dart' as _i6;
import 'package:bitblik_coordinator/src/models/pay_offer_result.dart' as _i9;
import 'package:bitblik_coordinator/src/services/database_service.dart' as _i10;
import 'package:bitblik_coordinator/src/services/payment_service.dart' as _i12;
import 'package:bitblik_core/core.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

import 'test_mocks.dart' as _i14;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeOutgoingPaymentAttempt_0 extends _i1.SmartFake
    implements _i2.OutgoingPaymentAttempt {
  _FakeOutgoingPaymentAttempt_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOffer_1 extends _i1.SmartFake implements _i3.Offer {
  _FakeOffer_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCreateHoldInvoiceResult_2 extends _i1.SmartFake
    implements _i4.CreateHoldInvoiceResult {
  _FakeCreateHoldInvoiceResult_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCancelInvoiceResult_3 extends _i1.SmartFake
    implements _i5.CancelInvoiceResult {
  _FakeCancelInvoiceResult_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePayInvoiceResult_4 extends _i1.SmartFake
    implements _i6.PayInvoiceResult {
  _FakePayInvoiceResult_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInvoiceDetails_5 extends _i1.SmartFake
    implements _i7.InvoiceDetails {
  _FakeInvoiceDetails_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBolt12OfferInfo_6 extends _i1.SmartFake
    implements _i8.Bolt12OfferInfo {
  _FakeBolt12OfferInfo_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePayOfferResult_7 extends _i1.SmartFake
    implements _i9.PayOfferResult {
  _FakePayOfferResult_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DatabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseService extends _i1.Mock implements _i10.DatabaseService {
  @override
  bool get recordStateHistory => (super.noSuchMethod(
        Invocation.getter(#recordStateHistory),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  set recordStateHistory(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #recordStateHistory,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i11.Future<void> connect() => (super.noSuchMethod(
        Invocation.method(
          #connect,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> disconnect() => (super.noSuchMethod(
        Invocation.method(
          #disconnect,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<_i2.OutgoingPaymentAttempt> getOrCreateOutgoingPaymentAttempt({
    required String? id,
    required String? offerId,
    required String? purpose,
    required _i2.OutgoingPaymentType? paymentType,
    required String? encoded,
    required int? expectedAmountSats,
    int? feeLimitSats,
    required String? backendType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrCreateOutgoingPaymentAttempt,
          [],
          {
            #id: id,
            #offerId: offerId,
            #purpose: purpose,
            #paymentType: paymentType,
            #encoded: encoded,
            #expectedAmountSats: expectedAmountSats,
            #feeLimitSats: feeLimitSats,
            #backendType: backendType,
          },
        ),
        returnValue: _i11.Future<_i2.OutgoingPaymentAttempt>.value(
            _FakeOutgoingPaymentAttempt_0(
          this,
          Invocation.method(
            #getOrCreateOutgoingPaymentAttempt,
            [],
            {
              #id: id,
              #offerId: offerId,
              #purpose: purpose,
              #paymentType: paymentType,
              #encoded: encoded,
              #expectedAmountSats: expectedAmountSats,
              #feeLimitSats: feeLimitSats,
              #backendType: backendType,
            },
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i2.OutgoingPaymentAttempt>.value(
                _FakeOutgoingPaymentAttempt_0(
          this,
          Invocation.method(
            #getOrCreateOutgoingPaymentAttempt,
            [],
            {
              #id: id,
              #offerId: offerId,
              #purpose: purpose,
              #paymentType: paymentType,
              #encoded: encoded,
              #expectedAmountSats: expectedAmountSats,
              #feeLimitSats: feeLimitSats,
              #backendType: backendType,
            },
          ),
        )),
      ) as _i11.Future<_i2.OutgoingPaymentAttempt>);

  @override
  _i11.Future<_i2.OutgoingPaymentAttempt> updateOutgoingPaymentAttempt(
    String? id, {
    required _i2.OutgoingPaymentAttemptState? state,
    String? backendPaymentId,
    String? paymentHash,
    String? preimage,
    String? payerProof,
    int? feePaidSats,
    String? failureReason,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateOutgoingPaymentAttempt,
          [id],
          {
            #state: state,
            #backendPaymentId: backendPaymentId,
            #paymentHash: paymentHash,
            #preimage: preimage,
            #payerProof: payerProof,
            #feePaidSats: feePaidSats,
            #failureReason: failureReason,
          },
        ),
        returnValue: _i11.Future<_i2.OutgoingPaymentAttempt>.value(
            _FakeOutgoingPaymentAttempt_0(
          this,
          Invocation.method(
            #updateOutgoingPaymentAttempt,
            [id],
            {
              #state: state,
              #backendPaymentId: backendPaymentId,
              #paymentHash: paymentHash,
              #preimage: preimage,
              #payerProof: payerProof,
              #feePaidSats: feePaidSats,
              #failureReason: failureReason,
            },
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i2.OutgoingPaymentAttempt>.value(
                _FakeOutgoingPaymentAttempt_0(
          this,
          Invocation.method(
            #updateOutgoingPaymentAttempt,
            [id],
            {
              #state: state,
              #backendPaymentId: backendPaymentId,
              #paymentHash: paymentHash,
              #preimage: preimage,
              #payerProof: payerProof,
              #feePaidSats: feePaidSats,
              #failureReason: failureReason,
            },
          ),
        )),
      ) as _i11.Future<_i2.OutgoingPaymentAttempt>);

  @override
  _i11.Future<void> recordOfferTransition({
    required String? offerId,
    required String? fromState,
    required String? toState,
    _i10.StateTransitionMeta? meta,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #recordOfferTransition,
          [],
          {
            #offerId: offerId,
            #fromState: fromState,
            #toState: toState,
            #meta: meta,
          },
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<List<Map<String, dynamic>>> getOfferStateHistory(
          String? offerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOfferStateHistory,
          [offerId],
        ),
        returnValue: _i11.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
        returnValueForMissingStub:
            _i11.Future<List<Map<String, dynamic>>>.value(
                <Map<String, dynamic>>[]),
      ) as _i11.Future<List<Map<String, dynamic>>>);

  @override
  _i11.Future<void> saveTelegramOfferMessage({
    required String? offerId,
    required String? chatId,
    required int? messageId,
    required String? messageText,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveTelegramOfferMessage,
          [],
          {
            #offerId: offerId,
            #chatId: chatId,
            #messageId: messageId,
            #messageText: messageText,
          },
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<List<_i10.TelegramOfferMessage>> getTelegramOfferMessages(
          String? offerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTelegramOfferMessages,
          [offerId],
        ),
        returnValue: _i11.Future<List<_i10.TelegramOfferMessage>>.value(
            <_i10.TelegramOfferMessage>[]),
        returnValueForMissingStub:
            _i11.Future<List<_i10.TelegramOfferMessage>>.value(
                <_i10.TelegramOfferMessage>[]),
      ) as _i11.Future<List<_i10.TelegramOfferMessage>>);

  @override
  _i11.Future<void> deleteTelegramOfferMessages(String? offerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteTelegramOfferMessages,
          [offerId],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> insertAuditLog({
    required String? level,
    required String? loggerName,
    required String? message,
    required String? action,
    String? offerId,
    String? error,
    String? stackTrace,
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertAuditLog,
          [],
          {
            #level: level,
            #loggerName: loggerName,
            #message: message,
            #action: action,
            #offerId: offerId,
            #error: error,
            #stackTrace: stackTrace,
            #metadata: metadata,
          },
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<_i3.Offer> createOffer(_i3.Offer? offer) => (super.noSuchMethod(
        Invocation.method(
          #createOffer,
          [offer],
        ),
        returnValue: _i11.Future<_i3.Offer>.value(_FakeOffer_1(
          this,
          Invocation.method(
            #createOffer,
            [offer],
          ),
        )),
        returnValueForMissingStub: _i11.Future<_i3.Offer>.value(_FakeOffer_1(
          this,
          Invocation.method(
            #createOffer,
            [offer],
          ),
        )),
      ) as _i11.Future<_i3.Offer>);

  @override
  _i11.Future<_i3.Offer?> getOfferById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getOfferById,
          [id],
        ),
        returnValue: _i11.Future<_i3.Offer?>.value(),
        returnValueForMissingStub: _i11.Future<_i3.Offer?>.value(),
      ) as _i11.Future<_i3.Offer?>);

  @override
  _i11.Future<_i3.Offer?> getOfferByPaymentHash(String? paymentHash) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOfferByPaymentHash,
          [paymentHash],
        ),
        returnValue: _i11.Future<_i3.Offer?>.value(),
        returnValueForMissingStub: _i11.Future<_i3.Offer?>.value(),
      ) as _i11.Future<_i3.Offer?>);

  @override
  _i11.Future<List<_i3.Offer>> getOffersByStatus(
    _i3.OfferStatus? status, {
    int? limit = 50,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOffersByStatus,
          [status],
          {
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue: _i11.Future<List<_i3.Offer>>.value(<_i3.Offer>[]),
        returnValueForMissingStub:
            _i11.Future<List<_i3.Offer>>.value(<_i3.Offer>[]),
      ) as _i11.Future<List<_i3.Offer>>);

  @override
  _i11.Future<List<_i3.Offer>> getOffersByRawStatus(
    String? status, {
    int? limit = 1000,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOffersByRawStatus,
          [status],
          {
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue: _i11.Future<List<_i3.Offer>>.value(<_i3.Offer>[]),
        returnValueForMissingStub:
            _i11.Future<List<_i3.Offer>>.value(<_i3.Offer>[]),
      ) as _i11.Future<List<_i3.Offer>>);

  @override
  _i11.Future<List<_i3.Offer>> getOffersNotInRawStatuses(
    List<String>? terminalStatuses, {
    int? limit = 5000,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOffersNotInRawStatuses,
          [terminalStatuses],
          {#limit: limit},
        ),
        returnValue: _i11.Future<List<_i3.Offer>>.value(<_i3.Offer>[]),
        returnValueForMissingStub:
            _i11.Future<List<_i3.Offer>>.value(<_i3.Offer>[]),
      ) as _i11.Future<List<_i3.Offer>>);

  @override
  _i11.Future<bool> updateOfferRawStatusIfCurrent(
    String? id,
    String? newStatus, {
    List<String>? expectedCurrentStatuses,
    String? expectedTakerPubkey,
    String? takerPubkey,
    String? code,
    String? takerInvoice,
    String? takerOffer,
    String? makerRefundInvoice,
    String? makerRefundOffer,
    DateTime? reservedAt,
    DateTime? codeReceivedAt,
    DateTime? takerChargedAt,
    DateTime? makerConfirmedAt,
    DateTime? settledAt,
    DateTime? takerPaidAt,
    DateTime? disputeAt,
    int? takerFees,
    int? takerInvoiceFees,
    String? failureReason,
    bool? clearTakerFields = false,
    bool? preserveCodeOnClear = false,
    _i10.StateTransitionMeta? transitionMeta,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateOfferRawStatusIfCurrent,
          [
            id,
            newStatus,
          ],
          {
            #expectedCurrentStatuses: expectedCurrentStatuses,
            #expectedTakerPubkey: expectedTakerPubkey,
            #takerPubkey: takerPubkey,
            #code: code,
            #takerInvoice: takerInvoice,
            #takerOffer: takerOffer,
            #makerRefundInvoice: makerRefundInvoice,
            #makerRefundOffer: makerRefundOffer,
            #reservedAt: reservedAt,
            #codeReceivedAt: codeReceivedAt,
            #takerChargedAt: takerChargedAt,
            #makerConfirmedAt: makerConfirmedAt,
            #settledAt: settledAt,
            #takerPaidAt: takerPaidAt,
            #disputeAt: disputeAt,
            #takerFees: takerFees,
            #takerInvoiceFees: takerInvoiceFees,
            #failureReason: failureReason,
            #clearTakerFields: clearTakerFields,
            #preserveCodeOnClear: preserveCodeOnClear,
            #transitionMeta: transitionMeta,
          },
        ),
        returnValue: _i11.Future<bool>.value(false),
        returnValueForMissingStub: _i11.Future<bool>.value(false),
      ) as _i11.Future<bool>);

  @override
  _i11.Future<List<_i3.Offer>> getMyActiveOffers(String? userPubkey) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMyActiveOffers,
          [userPubkey],
        ),
        returnValue: _i11.Future<List<_i3.Offer>>.value(<_i3.Offer>[]),
        returnValueForMissingStub:
            _i11.Future<List<_i3.Offer>>.value(<_i3.Offer>[]),
      ) as _i11.Future<List<_i3.Offer>>);

  @override
  _i11.Future<List<_i3.Offer>> getOffersFromLastHours() => (super.noSuchMethod(
        Invocation.method(
          #getOffersFromLastHours,
          [],
        ),
        returnValue: _i11.Future<List<_i3.Offer>>.value(<_i3.Offer>[]),
        returnValueForMissingStub:
            _i11.Future<List<_i3.Offer>>.value(<_i3.Offer>[]),
      ) as _i11.Future<List<_i3.Offer>>);
}

/// A class which mocks [PaymentService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaymentService extends _i1.Mock implements _i12.PaymentService {
  @override
  _i11.Future<void> connect() => (super.noSuchMethod(
        Invocation.method(
          #connect,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> disconnect() => (super.noSuchMethod(
        Invocation.method(
          #disconnect,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<_i4.CreateHoldInvoiceResult> createHoldInvoice({
    required int? amountSats,
    required String? memo,
    required String? paymentHashHex,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createHoldInvoice,
          [],
          {
            #amountSats: amountSats,
            #memo: memo,
            #paymentHashHex: paymentHashHex,
          },
        ),
        returnValue: _i11.Future<_i4.CreateHoldInvoiceResult>.value(
            _FakeCreateHoldInvoiceResult_2(
          this,
          Invocation.method(
            #createHoldInvoice,
            [],
            {
              #amountSats: amountSats,
              #memo: memo,
              #paymentHashHex: paymentHashHex,
            },
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i4.CreateHoldInvoiceResult>.value(
                _FakeCreateHoldInvoiceResult_2(
          this,
          Invocation.method(
            #createHoldInvoice,
            [],
            {
              #amountSats: amountSats,
              #memo: memo,
              #paymentHashHex: paymentHashHex,
            },
          ),
        )),
      ) as _i11.Future<_i4.CreateHoldInvoiceResult>);

  @override
  _i11.Future<void> settleInvoice({required String? preimageHex}) =>
      (super.noSuchMethod(
        Invocation.method(
          #settleInvoice,
          [],
          {#preimageHex: preimageHex},
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<_i5.CancelInvoiceResult> cancelInvoice(
          {required String? paymentHashHex}) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelInvoice,
          [],
          {#paymentHashHex: paymentHashHex},
        ),
        returnValue: _i11.Future<_i5.CancelInvoiceResult>.value(
            _FakeCancelInvoiceResult_3(
          this,
          Invocation.method(
            #cancelInvoice,
            [],
            {#paymentHashHex: paymentHashHex},
          ),
        )),
        returnValueForMissingStub: _i11.Future<_i5.CancelInvoiceResult>.value(
            _FakeCancelInvoiceResult_3(
          this,
          Invocation.method(
            #cancelInvoice,
            [],
            {#paymentHashHex: paymentHashHex},
          ),
        )),
      ) as _i11.Future<_i5.CancelInvoiceResult>);

  @override
  _i11.Future<_i6.PayInvoiceResult> payInvoice({
    required String? invoice,
    int? amountSat,
    int? feeLimitSat,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #payInvoice,
          [],
          {
            #invoice: invoice,
            #amountSat: amountSat,
            #feeLimitSat: feeLimitSat,
          },
        ),
        returnValue:
            _i11.Future<_i6.PayInvoiceResult>.value(_FakePayInvoiceResult_4(
          this,
          Invocation.method(
            #payInvoice,
            [],
            {
              #invoice: invoice,
              #amountSat: amountSat,
              #feeLimitSat: feeLimitSat,
            },
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i6.PayInvoiceResult>.value(_FakePayInvoiceResult_4(
          this,
          Invocation.method(
            #payInvoice,
            [],
            {
              #invoice: invoice,
              #amountSat: amountSat,
              #feeLimitSat: feeLimitSat,
            },
          ),
        )),
      ) as _i11.Future<_i6.PayInvoiceResult>);

  @override
  _i11.Stream<_i13.InvoiceUpdate> subscribeToInvoiceUpdates(
          {required String? paymentHashHex}) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribeToInvoiceUpdates,
          [],
          {#paymentHashHex: paymentHashHex},
        ),
        returnValue: _i11.Stream<_i13.InvoiceUpdate>.empty(),
        returnValueForMissingStub: _i11.Stream<_i13.InvoiceUpdate>.empty(),
      ) as _i11.Stream<_i13.InvoiceUpdate>);

  @override
  _i11.Future<_i7.InvoiceDetails> lookupInvoice(
          {required String? paymentHashHex}) =>
      (super.noSuchMethod(
        Invocation.method(
          #lookupInvoice,
          [],
          {#paymentHashHex: paymentHashHex},
        ),
        returnValue:
            _i11.Future<_i7.InvoiceDetails>.value(_FakeInvoiceDetails_5(
          this,
          Invocation.method(
            #lookupInvoice,
            [],
            {#paymentHashHex: paymentHashHex},
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i7.InvoiceDetails>.value(_FakeInvoiceDetails_5(
          this,
          Invocation.method(
            #lookupInvoice,
            [],
            {#paymentHashHex: paymentHashHex},
          ),
        )),
      ) as _i11.Future<_i7.InvoiceDetails>);

  @override
  _i11.Future<_i6.PayInvoiceResult?> reconcileOutgoingPayment(
          {required String? invoice}) =>
      (super.noSuchMethod(
        Invocation.method(
          #reconcileOutgoingPayment,
          [],
          {#invoice: invoice},
        ),
        returnValue: _i11.Future<_i6.PayInvoiceResult?>.value(),
        returnValueForMissingStub: _i11.Future<_i6.PayInvoiceResult?>.value(),
      ) as _i11.Future<_i6.PayInvoiceResult?>);
}

/// A class which mocks [CombinedPaymentService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCombinedPaymentService extends _i1.Mock
    implements _i14.CombinedPaymentService {
  @override
  bool get isBolt12Available => (super.noSuchMethod(
        Invocation.getter(#isBolt12Available),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i11.Future<void> connect() => (super.noSuchMethod(
        Invocation.method(
          #connect,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> disconnect() => (super.noSuchMethod(
        Invocation.method(
          #disconnect,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<_i4.CreateHoldInvoiceResult> createHoldInvoice({
    required int? amountSats,
    required String? memo,
    required String? paymentHashHex,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createHoldInvoice,
          [],
          {
            #amountSats: amountSats,
            #memo: memo,
            #paymentHashHex: paymentHashHex,
          },
        ),
        returnValue: _i11.Future<_i4.CreateHoldInvoiceResult>.value(
            _FakeCreateHoldInvoiceResult_2(
          this,
          Invocation.method(
            #createHoldInvoice,
            [],
            {
              #amountSats: amountSats,
              #memo: memo,
              #paymentHashHex: paymentHashHex,
            },
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i4.CreateHoldInvoiceResult>.value(
                _FakeCreateHoldInvoiceResult_2(
          this,
          Invocation.method(
            #createHoldInvoice,
            [],
            {
              #amountSats: amountSats,
              #memo: memo,
              #paymentHashHex: paymentHashHex,
            },
          ),
        )),
      ) as _i11.Future<_i4.CreateHoldInvoiceResult>);

  @override
  _i11.Future<void> settleInvoice({required String? preimageHex}) =>
      (super.noSuchMethod(
        Invocation.method(
          #settleInvoice,
          [],
          {#preimageHex: preimageHex},
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<_i5.CancelInvoiceResult> cancelInvoice(
          {required String? paymentHashHex}) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelInvoice,
          [],
          {#paymentHashHex: paymentHashHex},
        ),
        returnValue: _i11.Future<_i5.CancelInvoiceResult>.value(
            _FakeCancelInvoiceResult_3(
          this,
          Invocation.method(
            #cancelInvoice,
            [],
            {#paymentHashHex: paymentHashHex},
          ),
        )),
        returnValueForMissingStub: _i11.Future<_i5.CancelInvoiceResult>.value(
            _FakeCancelInvoiceResult_3(
          this,
          Invocation.method(
            #cancelInvoice,
            [],
            {#paymentHashHex: paymentHashHex},
          ),
        )),
      ) as _i11.Future<_i5.CancelInvoiceResult>);

  @override
  _i11.Future<_i6.PayInvoiceResult> payInvoice({
    required String? invoice,
    int? amountSat,
    int? feeLimitSat,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #payInvoice,
          [],
          {
            #invoice: invoice,
            #amountSat: amountSat,
            #feeLimitSat: feeLimitSat,
          },
        ),
        returnValue:
            _i11.Future<_i6.PayInvoiceResult>.value(_FakePayInvoiceResult_4(
          this,
          Invocation.method(
            #payInvoice,
            [],
            {
              #invoice: invoice,
              #amountSat: amountSat,
              #feeLimitSat: feeLimitSat,
            },
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i6.PayInvoiceResult>.value(_FakePayInvoiceResult_4(
          this,
          Invocation.method(
            #payInvoice,
            [],
            {
              #invoice: invoice,
              #amountSat: amountSat,
              #feeLimitSat: feeLimitSat,
            },
          ),
        )),
      ) as _i11.Future<_i6.PayInvoiceResult>);

  @override
  _i11.Stream<_i13.InvoiceUpdate> subscribeToInvoiceUpdates(
          {required String? paymentHashHex}) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribeToInvoiceUpdates,
          [],
          {#paymentHashHex: paymentHashHex},
        ),
        returnValue: _i11.Stream<_i13.InvoiceUpdate>.empty(),
        returnValueForMissingStub: _i11.Stream<_i13.InvoiceUpdate>.empty(),
      ) as _i11.Stream<_i13.InvoiceUpdate>);

  @override
  _i11.Future<_i7.InvoiceDetails> lookupInvoice(
          {required String? paymentHashHex}) =>
      (super.noSuchMethod(
        Invocation.method(
          #lookupInvoice,
          [],
          {#paymentHashHex: paymentHashHex},
        ),
        returnValue:
            _i11.Future<_i7.InvoiceDetails>.value(_FakeInvoiceDetails_5(
          this,
          Invocation.method(
            #lookupInvoice,
            [],
            {#paymentHashHex: paymentHashHex},
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i7.InvoiceDetails>.value(_FakeInvoiceDetails_5(
          this,
          Invocation.method(
            #lookupInvoice,
            [],
            {#paymentHashHex: paymentHashHex},
          ),
        )),
      ) as _i11.Future<_i7.InvoiceDetails>);

  @override
  _i11.Future<_i6.PayInvoiceResult?> reconcileOutgoingPayment(
          {required String? invoice}) =>
      (super.noSuchMethod(
        Invocation.method(
          #reconcileOutgoingPayment,
          [],
          {#invoice: invoice},
        ),
        returnValue: _i11.Future<_i6.PayInvoiceResult?>.value(),
        returnValueForMissingStub: _i11.Future<_i6.PayInvoiceResult?>.value(),
      ) as _i11.Future<_i6.PayInvoiceResult?>);

  @override
  _i11.Future<_i8.Bolt12OfferInfo> decodeOffer({required String? offer}) =>
      (super.noSuchMethod(
        Invocation.method(
          #decodeOffer,
          [],
          {#offer: offer},
        ),
        returnValue:
            _i11.Future<_i8.Bolt12OfferInfo>.value(_FakeBolt12OfferInfo_6(
          this,
          Invocation.method(
            #decodeOffer,
            [],
            {#offer: offer},
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i8.Bolt12OfferInfo>.value(_FakeBolt12OfferInfo_6(
          this,
          Invocation.method(
            #decodeOffer,
            [],
            {#offer: offer},
          ),
        )),
      ) as _i11.Future<_i8.Bolt12OfferInfo>);

  @override
  _i11.Future<_i9.PayOfferResult> payOffer({
    required String? offer,
    required int? amountSat,
    int? feeLimitSat,
    required String? paymentAttemptId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #payOffer,
          [],
          {
            #offer: offer,
            #amountSat: amountSat,
            #feeLimitSat: feeLimitSat,
            #paymentAttemptId: paymentAttemptId,
          },
        ),
        returnValue:
            _i11.Future<_i9.PayOfferResult>.value(_FakePayOfferResult_7(
          this,
          Invocation.method(
            #payOffer,
            [],
            {
              #offer: offer,
              #amountSat: amountSat,
              #feeLimitSat: feeLimitSat,
              #paymentAttemptId: paymentAttemptId,
            },
          ),
        )),
        returnValueForMissingStub:
            _i11.Future<_i9.PayOfferResult>.value(_FakePayOfferResult_7(
          this,
          Invocation.method(
            #payOffer,
            [],
            {
              #offer: offer,
              #amountSat: amountSat,
              #feeLimitSat: feeLimitSat,
              #paymentAttemptId: paymentAttemptId,
            },
          ),
        )),
      ) as _i11.Future<_i9.PayOfferResult>);

  @override
  _i11.Future<_i9.PayOfferResult?> reconcileOutgoingOffer({
    required String? offer,
    required String? paymentAttemptId,
    String? paymentId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #reconcileOutgoingOffer,
          [],
          {
            #offer: offer,
            #paymentAttemptId: paymentAttemptId,
            #paymentId: paymentId,
          },
        ),
        returnValue: _i11.Future<_i9.PayOfferResult?>.value(),
        returnValueForMissingStub: _i11.Future<_i9.PayOfferResult?>.value(),
      ) as _i11.Future<_i9.PayOfferResult?>);
}
