// Mocks generated by Mockito 5.4.6 from annotations
// in bitblik_coordinator/test/test_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:bitblik_coordinator/src/models/cancel_invoice_result.dart'
    as _i4;
import 'package:bitblik_coordinator/src/models/create_hold_invoice_result.dart'
    as _i3;
import 'package:bitblik_coordinator/src/models/invoice_details.dart' as _i6;
import 'package:bitblik_coordinator/src/models/invoice_update.dart' as _i10;
import 'package:bitblik_coordinator/src/models/pay_invoice_result.dart' as _i5;
import 'package:bitblik_coordinator/src/services/database_service.dart' as _i7;
import 'package:bitblik_coordinator/src/services/payment_service.dart' as _i9;
import 'package:bitblik_core/core.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeOffer_0 extends _i1.SmartFake implements _i2.Offer {
  _FakeOffer_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCreateHoldInvoiceResult_1 extends _i1.SmartFake
    implements _i3.CreateHoldInvoiceResult {
  _FakeCreateHoldInvoiceResult_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCancelInvoiceResult_2 extends _i1.SmartFake
    implements _i4.CancelInvoiceResult {
  _FakeCancelInvoiceResult_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePayInvoiceResult_3 extends _i1.SmartFake
    implements _i5.PayInvoiceResult {
  _FakePayInvoiceResult_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInvoiceDetails_4 extends _i1.SmartFake
    implements _i6.InvoiceDetails {
  _FakeInvoiceDetails_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DatabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseService extends _i1.Mock implements _i7.DatabaseService {
  @override
  bool get recordStateHistory => (super.noSuchMethod(
        Invocation.getter(#recordStateHistory),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  set recordStateHistory(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #recordStateHistory,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<void> connect() => (super.noSuchMethod(
        Invocation.method(
          #connect,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> disconnect() => (super.noSuchMethod(
        Invocation.method(
          #disconnect,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> recordOfferTransition({
    required String? offerId,
    required String? fromState,
    required String? toState,
    _i7.StateTransitionMeta? meta,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #recordOfferTransition,
          [],
          {
            #offerId: offerId,
            #fromState: fromState,
            #toState: toState,
            #meta: meta,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<List<Map<String, dynamic>>> getOfferStateHistory(
          String? offerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOfferStateHistory,
          [offerId],
        ),
        returnValue: _i8.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
        returnValueForMissingStub: _i8.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i8.Future<List<Map<String, dynamic>>>);

  @override
  _i8.Future<void> saveTelegramOfferMessage({
    required String? offerId,
    required String? chatId,
    required int? messageId,
    required String? messageText,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveTelegramOfferMessage,
          [],
          {
            #offerId: offerId,
            #chatId: chatId,
            #messageId: messageId,
            #messageText: messageText,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<List<_i7.TelegramOfferMessage>> getTelegramOfferMessages(
          String? offerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTelegramOfferMessages,
          [offerId],
        ),
        returnValue: _i8.Future<List<_i7.TelegramOfferMessage>>.value(
            <_i7.TelegramOfferMessage>[]),
        returnValueForMissingStub:
            _i8.Future<List<_i7.TelegramOfferMessage>>.value(
                <_i7.TelegramOfferMessage>[]),
      ) as _i8.Future<List<_i7.TelegramOfferMessage>>);

  @override
  _i8.Future<void> deleteTelegramOfferMessages(String? offerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteTelegramOfferMessages,
          [offerId],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> insertAuditLog({
    required String? level,
    required String? loggerName,
    required String? message,
    required String? action,
    String? offerId,
    String? error,
    String? stackTrace,
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertAuditLog,
          [],
          {
            #level: level,
            #loggerName: loggerName,
            #message: message,
            #action: action,
            #offerId: offerId,
            #error: error,
            #stackTrace: stackTrace,
            #metadata: metadata,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i2.Offer> createOffer(_i2.Offer? offer) => (super.noSuchMethod(
        Invocation.method(
          #createOffer,
          [offer],
        ),
        returnValue: _i8.Future<_i2.Offer>.value(_FakeOffer_0(
          this,
          Invocation.method(
            #createOffer,
            [offer],
          ),
        )),
        returnValueForMissingStub: _i8.Future<_i2.Offer>.value(_FakeOffer_0(
          this,
          Invocation.method(
            #createOffer,
            [offer],
          ),
        )),
      ) as _i8.Future<_i2.Offer>);

  @override
  _i8.Future<_i2.Offer?> getOfferById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getOfferById,
          [id],
        ),
        returnValue: _i8.Future<_i2.Offer?>.value(),
        returnValueForMissingStub: _i8.Future<_i2.Offer?>.value(),
      ) as _i8.Future<_i2.Offer?>);

  @override
  _i8.Future<_i2.Offer?> getOfferByPaymentHash(String? paymentHash) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOfferByPaymentHash,
          [paymentHash],
        ),
        returnValue: _i8.Future<_i2.Offer?>.value(),
        returnValueForMissingStub: _i8.Future<_i2.Offer?>.value(),
      ) as _i8.Future<_i2.Offer?>);

  @override
  _i8.Future<List<_i2.Offer>> getOffersByStatus(
    _i2.OfferStatus? status, {
    int? limit = 50,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOffersByStatus,
          [status],
          {
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue: _i8.Future<List<_i2.Offer>>.value(<_i2.Offer>[]),
        returnValueForMissingStub:
            _i8.Future<List<_i2.Offer>>.value(<_i2.Offer>[]),
      ) as _i8.Future<List<_i2.Offer>>);

  @override
  _i8.Future<List<_i2.Offer>> getOffersByRawStatus(
    String? status, {
    int? limit = 1000,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOffersByRawStatus,
          [status],
          {
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue: _i8.Future<List<_i2.Offer>>.value(<_i2.Offer>[]),
        returnValueForMissingStub:
            _i8.Future<List<_i2.Offer>>.value(<_i2.Offer>[]),
      ) as _i8.Future<List<_i2.Offer>>);

  @override
  _i8.Future<List<_i2.Offer>> getOffersNotInRawStatuses(
    List<String>? terminalStatuses, {
    int? limit = 5000,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOffersNotInRawStatuses,
          [terminalStatuses],
          {#limit: limit},
        ),
        returnValue: _i8.Future<List<_i2.Offer>>.value(<_i2.Offer>[]),
        returnValueForMissingStub:
            _i8.Future<List<_i2.Offer>>.value(<_i2.Offer>[]),
      ) as _i8.Future<List<_i2.Offer>>);

  @override
  _i8.Future<bool> updateOfferRawStatusIfCurrent(
    String? id,
    String? newStatus, {
    List<String>? expectedCurrentStatuses,
    String? expectedTakerPubkey,
    String? takerPubkey,
    String? code,
    String? takerInvoice,
    DateTime? reservedAt,
    DateTime? codeReceivedAt,
    DateTime? takerChargedAt,
    DateTime? makerConfirmedAt,
    DateTime? settledAt,
    DateTime? takerPaidAt,
    DateTime? disputeAt,
    int? takerFees,
    int? takerInvoiceFees,
    String? failureReason,
    bool? clearTakerFields = false,
    bool? preserveCodeOnClear = false,
    _i7.StateTransitionMeta? transitionMeta,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateOfferRawStatusIfCurrent,
          [
            id,
            newStatus,
          ],
          {
            #expectedCurrentStatuses: expectedCurrentStatuses,
            #expectedTakerPubkey: expectedTakerPubkey,
            #takerPubkey: takerPubkey,
            #code: code,
            #takerInvoice: takerInvoice,
            #reservedAt: reservedAt,
            #codeReceivedAt: codeReceivedAt,
            #takerChargedAt: takerChargedAt,
            #makerConfirmedAt: makerConfirmedAt,
            #settledAt: settledAt,
            #takerPaidAt: takerPaidAt,
            #disputeAt: disputeAt,
            #takerFees: takerFees,
            #takerInvoiceFees: takerInvoiceFees,
            #failureReason: failureReason,
            #clearTakerFields: clearTakerFields,
            #preserveCodeOnClear: preserveCodeOnClear,
            #transitionMeta: transitionMeta,
          },
        ),
        returnValue: _i8.Future<bool>.value(false),
        returnValueForMissingStub: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<List<_i2.Offer>> getMyActiveOffers(String? userPubkey) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMyActiveOffers,
          [userPubkey],
        ),
        returnValue: _i8.Future<List<_i2.Offer>>.value(<_i2.Offer>[]),
        returnValueForMissingStub:
            _i8.Future<List<_i2.Offer>>.value(<_i2.Offer>[]),
      ) as _i8.Future<List<_i2.Offer>>);

  @override
  _i8.Future<List<_i2.Offer>> getOffersFromLastHours() => (super.noSuchMethod(
        Invocation.method(
          #getOffersFromLastHours,
          [],
        ),
        returnValue: _i8.Future<List<_i2.Offer>>.value(<_i2.Offer>[]),
        returnValueForMissingStub:
            _i8.Future<List<_i2.Offer>>.value(<_i2.Offer>[]),
      ) as _i8.Future<List<_i2.Offer>>);
}

/// A class which mocks [PaymentService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaymentService extends _i1.Mock implements _i9.PaymentService {
  @override
  _i8.Future<void> connect() => (super.noSuchMethod(
        Invocation.method(
          #connect,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> disconnect() => (super.noSuchMethod(
        Invocation.method(
          #disconnect,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i3.CreateHoldInvoiceResult> createHoldInvoice({
    required int? amountSats,
    required String? memo,
    required String? paymentHashHex,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createHoldInvoice,
          [],
          {
            #amountSats: amountSats,
            #memo: memo,
            #paymentHashHex: paymentHashHex,
          },
        ),
        returnValue: _i8.Future<_i3.CreateHoldInvoiceResult>.value(
            _FakeCreateHoldInvoiceResult_1(
          this,
          Invocation.method(
            #createHoldInvoice,
            [],
            {
              #amountSats: amountSats,
              #memo: memo,
              #paymentHashHex: paymentHashHex,
            },
          ),
        )),
        returnValueForMissingStub:
            _i8.Future<_i3.CreateHoldInvoiceResult>.value(
                _FakeCreateHoldInvoiceResult_1(
          this,
          Invocation.method(
            #createHoldInvoice,
            [],
            {
              #amountSats: amountSats,
              #memo: memo,
              #paymentHashHex: paymentHashHex,
            },
          ),
        )),
      ) as _i8.Future<_i3.CreateHoldInvoiceResult>);

  @override
  _i8.Future<void> settleInvoice({required String? preimageHex}) =>
      (super.noSuchMethod(
        Invocation.method(
          #settleInvoice,
          [],
          {#preimageHex: preimageHex},
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i4.CancelInvoiceResult> cancelInvoice(
          {required String? paymentHashHex}) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelInvoice,
          [],
          {#paymentHashHex: paymentHashHex},
        ),
        returnValue: _i8.Future<_i4.CancelInvoiceResult>.value(
            _FakeCancelInvoiceResult_2(
          this,
          Invocation.method(
            #cancelInvoice,
            [],
            {#paymentHashHex: paymentHashHex},
          ),
        )),
        returnValueForMissingStub: _i8.Future<_i4.CancelInvoiceResult>.value(
            _FakeCancelInvoiceResult_2(
          this,
          Invocation.method(
            #cancelInvoice,
            [],
            {#paymentHashHex: paymentHashHex},
          ),
        )),
      ) as _i8.Future<_i4.CancelInvoiceResult>);

  @override
  _i8.Future<_i5.PayInvoiceResult> payInvoice({
    required String? invoice,
    int? amountSat,
    int? feeLimitSat,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #payInvoice,
          [],
          {
            #invoice: invoice,
            #amountSat: amountSat,
            #feeLimitSat: feeLimitSat,
          },
        ),
        returnValue:
            _i8.Future<_i5.PayInvoiceResult>.value(_FakePayInvoiceResult_3(
          this,
          Invocation.method(
            #payInvoice,
            [],
            {
              #invoice: invoice,
              #amountSat: amountSat,
              #feeLimitSat: feeLimitSat,
            },
          ),
        )),
        returnValueForMissingStub:
            _i8.Future<_i5.PayInvoiceResult>.value(_FakePayInvoiceResult_3(
          this,
          Invocation.method(
            #payInvoice,
            [],
            {
              #invoice: invoice,
              #amountSat: amountSat,
              #feeLimitSat: feeLimitSat,
            },
          ),
        )),
      ) as _i8.Future<_i5.PayInvoiceResult>);

  @override
  _i8.Stream<_i10.InvoiceUpdate> subscribeToInvoiceUpdates(
          {required String? paymentHashHex}) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribeToInvoiceUpdates,
          [],
          {#paymentHashHex: paymentHashHex},
        ),
        returnValue: _i8.Stream<_i10.InvoiceUpdate>.empty(),
        returnValueForMissingStub: _i8.Stream<_i10.InvoiceUpdate>.empty(),
      ) as _i8.Stream<_i10.InvoiceUpdate>);

  @override
  _i8.Future<_i6.InvoiceDetails> lookupInvoice(
          {required String? paymentHashHex}) =>
      (super.noSuchMethod(
        Invocation.method(
          #lookupInvoice,
          [],
          {#paymentHashHex: paymentHashHex},
        ),
        returnValue: _i8.Future<_i6.InvoiceDetails>.value(_FakeInvoiceDetails_4(
          this,
          Invocation.method(
            #lookupInvoice,
            [],
            {#paymentHashHex: paymentHashHex},
          ),
        )),
        returnValueForMissingStub:
            _i8.Future<_i6.InvoiceDetails>.value(_FakeInvoiceDetails_4(
          this,
          Invocation.method(
            #lookupInvoice,
            [],
            {#paymentHashHex: paymentHashHex},
          ),
        )),
      ) as _i8.Future<_i6.InvoiceDetails>);

  @override
  _i8.Future<_i5.PayInvoiceResult?> reconcileOutgoingPayment(
          {required String? invoice}) =>
      (super.noSuchMethod(
        Invocation.method(
          #reconcileOutgoingPayment,
          [],
          {#invoice: invoice},
        ),
        returnValue: _i8.Future<_i5.PayInvoiceResult?>.value(),
        returnValueForMissingStub: _i8.Future<_i5.PayInvoiceResult?>.value(),
      ) as _i8.Future<_i5.PayInvoiceResult?>);
}
