name: bitblik_monorepos
publish_to: none

environment:
  sdk: ^3.11.0

dependency_overrides:
  ndk:
    git: {
      url: https://github.com/relaystr/ndk.git,
      path: packages/ndk,
      ref: c7a42927c20fec9bdfe65b06e1d7e49c6495b68c
    }
  ndk_flutter:
    git: {
      url: https://github.com/relaystr/ndk.git,
      path: packages/ndk_flutter,
      ref: c7a42927c20fec9bdfe65b06e1d7e49c6495b68c
    }
  ndk_drift:
    git: {
      url: https://github.com/relaystr/ndk.git,
      path: packages/drift,
      ref: c7a42927c20fec9bdfe65b06e1d7e49c6495b68c
    }
  ndk_objectbox:
    git: {
      url: https://github.com/relaystr/ndk.git,
      path: packages/objectbox,
      ref: c7a42927c20fec9bdfe65b06e1d7e49c6495b68c
    }
workspace:
  - packages/app
  - packages/cli
  - packages/coordinator
  - packages/core
  - packages/telegram_bot
