name: bitblik_monorepos
publish_to: none

environment:
  sdk: ^3.11.0

dependency_overrides:
  # NIP-82 support plus native WebSocket compression opt-out for long-running
  # services.
  ndk:
    git: {
      url: https://github.com/relaystr/ndk.git,
      path: packages/ndk,
      ref: 6335af2cee4d6658d42ba976f51f826234dfb1a7
    }
  ndk_flutter:
    git: {
      url: https://github.com/relaystr/ndk.git,
      path: packages/ndk_flutter,
      ref: 6335af2cee4d6658d42ba976f51f826234dfb1a7
    }
  ndk_drift:
    git: {
      url: https://github.com/relaystr/ndk.git,
      path: packages/drift,
      ref: 6335af2cee4d6658d42ba976f51f826234dfb1a7
    }
  ndk_objectbox:
    git: {
      url: https://github.com/relaystr/ndk.git,
      path: packages/objectbox,
      ref: 6335af2cee4d6658d42ba976f51f826234dfb1a7
    }
workspace:
  - packages/app
  - packages/cli
  - packages/coordinator
  - packages/core
  - packages/telegram_bot
